title: SoloBits
tagline: 'Share | Learn | Contribute'
description: >- # this means to ignore newlines until "baseurl:"
  SHARING WHAT I KNOW AND CONTRIBUTING TO THE DEV. COMMUNITY
baseurl: ""
twitter_username: ""
github_username: solobits
name: SoloBits

paginate: 5
permalink:           pretty

author:
  name: Nelson John
  url:  http://linkedin.com/in/solobits/
  email: nelson_john@icloud.com
